language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ng-scaffold' ]; then cd .. && eval "mv $currentfolder generator-ng-scaffold" && cd generator-ng-scaffold; fi

